// mockups/shadcn-react-sample/src/routes/components/destructive-confirmation.tsx
import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogTrigger
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Showcase, ShowcaseRow } from "@/components/showcase";

export const Route = createFileRoute("/components/destructive-confirmation")({ component: Page });

const CONFIRMATION_TEXT = "production";

function Page() {
  const [open, setOpen] = useState(false);
  const [typed, setTyped] = useState("");
  const [result, setResult] = useState("Resource is still present.");
  const canConfirm = typed === CONFIRMATION_TEXT;

  function handleOpenChange(next: boolean) {
    setOpen(next);
    if (!next) setTyped("");
  }

  function confirm() {
    if (!canConfirm) return;
    setResult("Environment deletion confirmed.");
    handleOpenChange(false);
  }

  return (
    <Showcase
      title="Destructive confirmation sample"
      designDoc="DESIGN.md → design/overlays/modal-confirmation.md"
      description="Two-step destructive confirmation requiring typed text."
    >
      <ShowcaseRow title="Delete environment">
        <div className="grid w-full gap-3">
          <Dialog open={open} onOpenChange={handleOpenChange}>
            <DialogTrigger asChild>
              <Button variant="destructive" className="w-fit">
                Delete environment
              </Button>
            </DialogTrigger>
            <DialogContent>
              <div className="rounded-sm border border-red-200 bg-red-50 p-3 dark:border-red-900 dark:bg-red-950/30">
                <div className="flex items-start justify-between gap-4">
                  <h2 className="text-xl font-bold text-red-800 dark:text-red-300">
                    Delete environment?
                  </h2>
                </div>
                <p className="mt-2 text-sm text-red-700 dark:text-red-300/90">
                  All resources inside this environment will be permanently deleted. This cannot be
                  undone.
                </p>
              </div>

              <label
                className="mt-4 block text-sm text-neutral-700 dark:text-neutral-300"
                htmlFor="confirmation-text"
              >
                Type{" "}
                <span className="font-mono font-bold text-black dark:text-white">
                  {CONFIRMATION_TEXT}
                </span>{" "}
                to confirm.
              </label>
              <Input
                id="confirmation-text"
                className="mt-2 dark:bg-app-base"
                value={typed}
                onChange={(e) => setTyped(e.target.value)}
                placeholder={CONFIRMATION_TEXT}
              />

              <DialogFooter className="mt-5">
                <DialogClose asChild>
                  <Button>Cancel</Button>
                </DialogClose>
                <Button variant="destructive" disabled={!canConfirm} onClick={confirm}>
                  Delete environment
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
          <p className="text-sm text-neutral-600 dark:text-neutral-400">{result}</p>
        </div>
      </ShowcaseRow>
    </Showcase>
  );
}

// mockups/shadcn-svelte-sample/src/lib/components/ui/modal/destructive-confirmation.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";

  export let open = false;
  export let title = "Confirm destructive action";
  export let description = "This action is permanent and cannot be undone.";
  export let confirmationText = "DELETE";
  export let cancelLabel = "Cancel";
  export let confirmLabel = "Delete";
  export let onconfirm: () => void = () => {};

  let typed = "";
  $: canConfirm = typed === confirmationText;

  function close() {
    open = false;
    typed = "";
  }

  function confirm() {
    if (!canConfirm) return;
    onconfirm();
    close();
  }
</script>

{#if open}
  <div class="fixed inset-0 z-50 flex items-center justify-center p-4" role="presentation">
    <button class="absolute inset-0 cursor-default bg-black/60 backdrop-blur-[1px]" aria-label="Cancel destructive confirmation" onclick={close}></button>
    <div role="alertdialog" aria-modal="true" aria-labelledby="destructive-title" aria-describedby="destructive-description" class="relative z-10 w-full max-w-lg rounded-sm border border-neutral-200 bg-white p-4 shadow-xl dark:border-coolgray-300 dark:bg-coolgray-100">
      <div class="rounded-sm border border-red-200 bg-red-50 p-3 dark:border-red-900 dark:bg-red-950/30">
        <div class="flex items-start justify-between gap-4"><h2 id="destructive-title" class="text-xl font-bold text-red-800 dark:text-red-300">{title}</h2><Button variant="ghost" size="icon" aria-label="Close destructive confirmation" onclick={close}>×</Button></div>
        <p id="destructive-description" class="mt-2 text-sm text-red-700 dark:text-red-300/90">{description}</p>
      </div>

      <label class="mt-4 block text-sm text-neutral-700 dark:text-neutral-300" for="confirmation-text">
        Type <span class="font-mono font-bold text-black dark:text-white">{confirmationText}</span> to confirm.
      </label>
      <Input id="confirmation-text" class="mt-2 dark:bg-app-base" bind:value={typed} placeholder={confirmationText} />

      <div class="mt-5 flex flex-wrap justify-end gap-2">
        <Button onclick={close}>{cancelLabel}</Button>
        <Button variant="destructive" disabled={!canConfirm} onclick={confirm}>{confirmLabel}</Button>
      </div>
    </div>
  </div>
{/if}
