// mockups/shadcn-svelte-sample/src/lib/components/ui/auth-pages/confirm-password-page.svelte
<script lang="ts">
  import AuthPrimaryButton from "./auth-primary-button.svelte";
  import { PasswordInput } from "$lib/components/ui/input/index.js";
  import { FormField } from "$lib/components/ui/form-field/index.js";

  let password = "";
  let submitted = false;
</script>

<section data-slot="auth-pages" class="mx-auto w-full max-w-md space-y-8 text-foreground">
  <div class="space-y-2 text-center"><h2 class="text-5xl font-extrabold tracking-tight">Coolify</h2><p class="text-lg text-muted-foreground">Confirm Your Password</p></div>
  <div class="space-y-6">
    <div class="rounded-sm border border-border bg-muted p-4"><div class="flex gap-3"><span class="mt-0.5 font-bold text-primary">i</span><p class="text-sm text-muted-foreground">This is a secure area. Please confirm your password before continuing.</p></div></div>
    <form class="flex flex-col gap-4" onsubmit={(event) => { event.preventDefault(); submitted = true; }}>
      <FormField forId="confirm-password" label="Password" required><PasswordInput id="confirm-password" autocomplete="current-password" bind:value={password} /></FormField>
      <AuthPrimaryButton type="submit" disabled={password.length === 0}>Confirm password</AuthPrimaryButton>
    </form>
    {#if submitted}<div class="rounded-sm border border-green-200 bg-green-50 p-3 text-sm text-green-800 dark:border-green-900 dark:bg-green-950/30 dark:text-green-300">Password confirmation submitted.</div>{/if}
  </div>
</section>

// mockups/shadcn-react-sample/src/routes/pages/confirm-password-page.tsx
import { useState, type FormEvent } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { PasswordInput } from "@/components/ui/input";
import { FormField } from "@/components/ui/form-field";
import {
  AuthCard,
  AuthHeader,
  AuthInfoBox,
  AuthPrimaryButton,
  AuthShell,
  AuthSuccess,
} from "@/components/ui/auth-shell";

export const Route = createFileRoute("/pages/confirm-password-page")({
  component: Page,
});

function Page() {
  const [password, setPassword] = useState("");
  const [submitted, setSubmitted] = useState(false);

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitted(true);
  }

  return (
    <AuthShell>
      <AuthCard>
        <AuthHeader subtitle="Confirm Your Password" />

        <div className="space-y-6">
          <AuthInfoBox>
            This is a secure area. Please confirm your password before
            continuing.
          </AuthInfoBox>
          <form className="flex flex-col gap-4" onSubmit={handleSubmit}>
            <FormField label="Password" required>
              <PasswordInput
                id="confirm-password"
                autoComplete="current-password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
              />
            </FormField>
            <AuthPrimaryButton type="submit" disabled={password.length === 0}>
              Confirm password
            </AuthPrimaryButton>
          </form>
          {submitted && (
            <AuthSuccess>Password confirmation submitted.</AuthSuccess>
          )}
        </div>
      </AuthCard>
    </AuthShell>
  );
}
