// mockups/shadcn-svelte-sample/src/lib/components/ui/auth-pages/register-page.svelte
<script lang="ts">
  import AuthPrimaryButton from "./auth-primary-button.svelte";
  import { Input, PasswordInput } from "$lib/components/ui/input/index.js";
  import { FormField } from "$lib/components/ui/form-field/index.js";

  export let firstUser = true;

  let name = "test normal user";
  let email = "test@example.com";
  let password = "";
  let passwordConfirmation = "";
  let submitted = false;

  $: passwordMismatch = passwordConfirmation.length > 0 && password !== passwordConfirmation ? "Passwords must match." : "";
  $: canSubmit = name.length > 0 && email.length > 0 && password.length >= 8 && password === passwordConfirmation;
</script>

<section class="mx-auto w-full max-w-md space-y-8 text-black dark:text-white">
  <div class="space-y-2 text-center">
    <h2 class="text-5xl font-extrabold tracking-tight text-gray-900 dark:text-white">Coolify</h2>
    <p class="text-lg text-neutral-600 dark:text-neutral-400">Create your account</p>
  </div>

  <div class="space-y-6">
    {#if firstUser}
      <div class="rounded-sm border border-warning bg-warning/10 p-4">
        <div class="flex gap-3">
          <span class="mt-0.5 size-5 shrink-0 text-warning" aria-hidden="true">✓</span>
          <div>
            <p class="font-bold text-warning">Root User Setup</p>
            <p class="text-sm text-black dark:text-white">This user will be the root user with full admin access.</p>
          </div>
        </div>
      </div>
    {/if}

    <form class="flex flex-col gap-4" onsubmit={(event) => { event.preventDefault(); submitted = true; }}>
      <FormField forId="register-name" label="Name" required>
        <Input id="register-name" autocomplete="name" bind:value={name} />
      </FormField>

      <FormField forId="register-email" label="Email" required>
        <Input id="register-email" type="email" autocomplete="email" bind:value={email} />
      </FormField>

      <FormField forId="register-password" label="Password" required>
        <PasswordInput id="register-password" autocomplete="new-password" bind:value={password} />
      </FormField>

      <FormField forId="register-password-confirmation" label="Password again" required error={passwordMismatch || undefined}>
        <PasswordInput id="register-password-confirmation" autocomplete="new-password" bind:value={passwordConfirmation} aria-invalid={!!passwordMismatch} />
      </FormField>

      <div class="rounded-sm border border-neutral-200 bg-neutral-50 p-4 dark:border-coolgray-300 dark:bg-coolgray-100">
        <p class="text-xs text-neutral-600 dark:text-neutral-400">Your password should be min 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one symbol.</p>
      </div>

      <AuthPrimaryButton class="mt-2" type="submit" disabled={!canSubmit}>Create Account</AuthPrimaryButton>
    </form>

    {#if submitted}
      <div class="rounded-sm border border-green-200 bg-green-50 p-3 text-sm text-green-800 dark:border-green-900 dark:bg-green-950/30 dark:text-green-300">Account creation submitted for {email}.</div>
    {/if}

    <div class="relative my-6">
      <div class="absolute inset-0 flex items-center"><div class="w-full border-t border-neutral-300 dark:border-coolgray-300"></div></div>
      <div class="relative flex justify-center text-sm"><span class="bg-gray-50 px-2 text-neutral-500 dark:bg-base dark:text-neutral-400">Already have an account?</span></div>
    </div>

    <a href="/pages/login-page" class="block w-full rounded-sm border border-neutral-300 px-4 py-3 text-center font-medium transition-colors hover:border-coollabs dark:border-coolgray-300 dark:hover:border-warning">Already registered?</a>
  </div>
</section>

// mockups/shadcn-react-sample/src/routes/pages/register-page.tsx
import { useState, type FormEvent } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Input, PasswordInput } from "@/components/ui/input";
import { FormField } from "@/components/ui/form-field";
import {
  AuthCard,
  AuthDivider,
  AuthHeader,
  AuthInfoBox,
  AuthPrimaryButton,
  AuthSecondaryLink,
  AuthShell,
  AuthSuccess,
} from "@/components/ui/auth-shell";

export const Route = createFileRoute("/pages/register-page")({ component: Page });

function Page() {
  const firstUser = true;
  const [name, setName] = useState("test normal user");
  const [email, setEmail] = useState("test@example.com");
  const [password, setPassword] = useState("");
  const [passwordConfirmation, setPasswordConfirmation] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const passwordMismatch =
    passwordConfirmation.length > 0 && password !== passwordConfirmation
      ? "Passwords must match."
      : "";
  const canSubmit =
    name.length > 0 &&
    email.length > 0 &&
    password.length >= 8 &&
    password === passwordConfirmation;

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitted(true);
  }

  return (
    <AuthShell>
      <AuthCard>
        <AuthHeader subtitle="Create your account" />

        <div className="space-y-6">
          {firstUser && (
            <div className="rounded-sm border border-warning bg-warning/10 p-4">
              <div className="flex gap-3">
                <span
                  className="mt-0.5 size-5 shrink-0 text-warning"
                  aria-hidden="true"
                >
                  ✓
                </span>
                <div>
                  <p className="font-bold text-warning">Root User Setup</p>
                  <p className="text-sm text-black dark:text-white">
                    This user will be the root user with full admin access.
                  </p>
                </div>
              </div>
            </div>
          )}

          <form className="flex flex-col gap-4" onSubmit={handleSubmit}>
            <FormField label="Name" required>
              <Input
                id="register-name"
                autoComplete="name"
                value={name}
                onChange={(event) => setName(event.target.value)}
              />
            </FormField>

            <FormField label="Email" required>
              <Input
                id="register-email"
                type="email"
                autoComplete="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
              />
            </FormField>

            <FormField label="Password" required>
              <PasswordInput
                id="register-password"
                autoComplete="new-password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
              />
            </FormField>

            <FormField
              label="Password again"
              required
              error={passwordMismatch || undefined}
            >
              <PasswordInput
                id="register-password-confirmation"
                autoComplete="new-password"
                value={passwordConfirmation}
                aria-invalid={passwordMismatch ? true : undefined}
                onChange={(event) =>
                  setPasswordConfirmation(event.target.value)
                }
              />
            </FormField>

            <AuthInfoBox>
              <p className="text-xs text-neutral-600 dark:text-neutral-400">
                Your password should be min 8 characters long and contain at
                least one uppercase letter, one lowercase letter, one number,
                and one symbol.
              </p>
            </AuthInfoBox>

            <AuthPrimaryButton
              className="mt-2"
              type="submit"
              disabled={!canSubmit}
            >
              Create Account
            </AuthPrimaryButton>
          </form>

          {submitted && (
            <AuthSuccess>Account creation submitted for {email}.</AuthSuccess>
          )}

          <AuthDivider>Already have an account?</AuthDivider>

          <AuthSecondaryLink href="/pages/login-page">
            Already registered?
          </AuthSecondaryLink>
        </div>
      </AuthCard>
    </AuthShell>
  );
}
